language: node_js
node_js:
  - "10"

branches:
  only:
    - develop

install:
  - npm install

script:
  - npm run lint
  - npm run build

notifications:
  email:
    recipients:
    - ziga@be-codified.com
    on_success: change
    on_failure: always

cache:
  directories:
    - node_modules
